# Generated by Django 5.1 on 2024-09-05 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CSVFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_hash",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CSVRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("impression_id", models.UUIDField()),
                (
                    "impression_city",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("posting_user_id", models.IntegerField(blank=True, null=True)),
                ("post_id", models.IntegerField(blank=True, null=True)),
                (
                    "viewer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "impression_country",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("device", models.CharField(blank=True, max_length=50, null=True)),
                ("data", models.JSONField(blank=True, null=True)),
                (
                    "csv_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="api.csvfile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GenericData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_id", models.UUIDField()),
                ("file_id", models.IntegerField(blank=True, null=True)),
                ("selected_column", models.CharField(max_length=255)),
                ("second_dropdown_value", models.CharField(max_length=255)),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["file_id"], name="api_generic_file_id_e39c2b_idx"
                    )
                ],
            },
        ),
    ]
