repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: bash -c "cd backend && poetry run black ."
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: bash -c "cd backend && poetry run isort ."
        language: system
        types: [python]

      - id: pytest
        name: pytest
        entry: bash -c "cd backend && poetry run pytest"
        language: system
        pass_filenames: false
        always_run: true
