repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: bash -c "cd backend && poetry run black ."
        language: system
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

# TODO: disabled for now due to migration files not being generated
      # - id: pytest
      #   name: pytest
      #   entry: bash -c "cd backend && poetry run pytest"
      #   language: system
      #   pass_filenames: false
      #   always_run: true
