services:
  db:
    image: postgres:13
    tmpfs:
      - /var/lib/postgresql/data
    env_file:
      - ./backend/.env
    networks:
      - app-network
    ports:
      - "5432:5432"
      - "5433:5433"

  redis:
    image: redis:latest
    networks:
      - app-network

  celery:
    build:
      context: ./backend
    command: celery -A api worker --loglevel=info
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - app-network
    depends_on:
      - db
      - redis

  beat:
    build:
      context: ./backend
    command: celery -A api beat --loglevel=info
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - app-network
    depends_on:
      - db
      - redis

  zookeeper:
    image: bitnami/zookeeper:3.7
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-network
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:2.8
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - app-network
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
