services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - app-network
    depends_on:
      - db
      - redis
      - celery

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - app-network

  db:
    image: postgres:13
    tmpfs:
      - /var/lib/postgresql/data
    env_file:
      - ./backend/.env
    networks:
      - app-network
    ports:
      - "5432:5432"
      - "5433:5433"

  redis:
    image: redis:latest
    networks:
      - app-network

  celery:
    build:
      context: ./backend
    command: celery -A api worker --loglevel=info
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - app-network
    depends_on:
      - db
      - redis

  beat:
    build:
      context: ./backend
    command: celery -A api beat --loglevel=info
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - app-network
    depends_on:
      - db
      - redis

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
